services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend/clinic-charges-app
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/clinic-charges-app:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clinic_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: